{{ if .Values.mysql.enabled }}

{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "froxlor.fullname" . }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "froxlor.fullname" . }}
      component: mysql
  template:
    metadata:
      labels:
        app: {{ include "froxlor.fullname" . }}
        component: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        args:
          - --character-set-server=utf8
          - --collation-server=utf8_unicode_ci
        volumeMounts:
          - name: data
            subPath: mysql
            mountPath: /var/lib/mysql
        env:
          {{ if .Values.mysql.rootPassword }}
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysql.rootPassword }}
          {{ else }}
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          {{ end }}
          - name: MYSQL_DATABASE
            value: {{ required "mysql.database" .Values.mysql.database }}
          - name: MYSQL_USER
            value: {{ required "mysql.user" .Values.mysql.user }}
          - name: MYSQL_PASSWORD
            value: {{ required "mysql.password" .Values.mysql.password }}
        ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "froxlor.fullname" . }}-storage
  strategy:
    # This is a single-node mysql instance, so we need to shut down the old instance before starting a new
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "froxlor.fullname" . }}-mysql
  labels:
    app: {{ include "froxlor.fullname" . }}
    component: mysql
spec:
  selector:
    app: {{ include "froxlor.fullname" . }}
    component: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP

{{ end }}
